name: engelsburg_app
description: Eine App von Dario Trombello, die Informationen über das Engelsburg-Gymnasium übersichtlich zusammenstellt.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.6.4+25

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.1
  device_info_plus: ^4.0.0
  google_maps_flutter: ^2.1.8
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  weather_icons: ^3.0.0
  flutter_riverpod: ^1.0.4
  flutter_widget_from_html_core: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
