name: engelsburg_app
description: Eine App von Dario Trombello, die Informationen über das Engelsburg-Gymnasium übersichtlich zusammenstellt.
publish_to: 'none'
version: 1.5.5+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.1.0+1
  flutter_widget_from_html_core: ^0.8.1
  google_maps_flutter: ^2.1.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  native_pdf_view: ^5.0.0
  package_info_plus: ^1.3.0
  share_plus: ^3.0.4
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true

  assets:
   - assets/documents/schuelerzeitung.pdf
   - assets/images/applogo.png
   - assets/images/logoengelsburg.png
   - assets/images/school.jpg
   - assets/images/weather-background.jpg

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Black.ttf
          weight: 900
